#! /bin/sh

RED="\033[31m"
RESET="\033[0m"

usbttycan() {
    echo "Setup a USB TTY CAN device"
    echo "Please type device path (default: /dev/ttyUSB0)"
    read -r dev
    # set dev default value to /dev/ttyUSB0
    dev=${dev:="/dev/ttyUSB0"} 

    echo "setup device $dev"
    sudo chmod 777 $dev
}

CANable() {
    echo "Unsupport now please wait"
    exit -1
}

origin() {
    echo "Setup original CAN for ${RED}Nvidia Jetson AGX Xavier${RESET}"
    path=`which busybox`
    if [ -z path ]; then
        echo "Please install busybox first!"
        echo "${RED}sudo apt install busybox${RESET}"
        exit -1
    fi
    echo "Please type CAN if name (default: can0)"
    read -r dev
    # set dev default value to can0
    dev=${dev:="can0"}

    if [ $dev = "can0" ]; then
        # set up can0 pinmux 
        sudo busybox devmem 0x0c303018 w 0xc458
        sudo busybox devmem 0x0c303010 w 0xc400
    elif [ $dev = "can1" ]; then
        # set up can1 pinmux
        sudo busybox devmem 0x0c303008 w 0xc458
        sudo busybox devmem 0x0c303000 w 0xc400
    else
        echo "Current only support ${RED}can0 can1${RESET}!"
        exit -1;
    fi
    # ins mod
    sudo modprobe can
    sudo modprobe can_raw
    sudo modprobe mttcan 
    sudo ip link set $dev up type can bitrate 500000
}

echo "Please select setup device type (default: 1)"
echo "1: USB TTY CAN"
echo "2: CANable (${RED}Unsupport yet!${RESET})"
echo "3: ORIGIN (Nvidia Jetson)"

read -r type

if [ -z $type ]; then
    type=1
fi

case $type in
    1) usbttycan ;;
    2) CAnable ;;
    3) origin ;;
    *) echo "Not support type" ;;
esac

echo ""
