#! /bin/sh

RED="\033[31m"
RESET="\033[0m"

usbttycan() {
    echo "Setup a USB-TTY-CAN device"
    echo "Please type device path (default: /dev/ttyUSB0)"
    read -r dev
    # set dev default value to /dev/ttyUSB0
    dev=${dev:="/dev/ttyUSB0"} 

    echo "setup device $dev"
    sudo chmod 777 $dev
}

CANable() {
    pcan() {
        echo "Setup a pcan-CANable device"
        sudo modprobe peak_usb
        echo "Please type CAN if name (default: can0)"
        read -r can 
        # set can default value to can0
        can=${can:="can0"}
        sudo ip link set $can up type can bitrate 500000
    }

    slcan() {
        echo "Setup a slcan-CANable device"
        echo "Please type serial path (default: /dev/ttyACM0)"
        read -r dev
        # set dev default value to /dev/ttyACM0
        dev=${dev:="/dev/ttyACM0"}

        echo "Please type CAN if name (default: can0)"
        read -r can
        # set can default value to can0
        can=${can:="can0"}

        sudo slcand -foc -s6 $dev $can 
        sudo ip link set $can up 
    }

    echo "Setup a CANable device"
    echo "Please select type (default: 1)"
    echo "1: pcan"
    echo "2: slcan"

    read -r type
    type=${type:=1}

    case $type in
        1) pcan;;
        2) slcan;;
        *) echo "Not support type" ;;
    esac

}

origin() {
    echo "Setup original CAN for ${RED}Nvidia Jetson${RESET}"
    path=`which busybox`
    if [ -z path ]; then
        echo "Please install busybox first!"
        echo "${RED}sudo apt install busybox${RESET}"
        exit -1
    fi
    echo "Please type CAN if name (default: can0)"
    read -r can 
    # set can default value to can0
    can=${can:="can0"}

    if [ $can = "can0" ]; then
        # set up can0 pinmux 
        sudo busybox devmem 0x0c303018 w 0xc458
        sudo busybox devmem 0x0c303010 w 0xc400
    elif [ $can = "can1" ]; then
        # set up can1 pinmux
        sudo busybox devmem 0x0c303008 w 0xc458
        sudo busybox devmem 0x0c303000 w 0xc400
    else
        echo "Current only support ${RED}can0 can1${RESET}!"
        exit -1;
    fi
    # ins mod
    sudo modprobe can
    sudo modprobe can_raw
    sudo modprobe mttcan 
    sudo ip link set $can up type can bitrate 500000
}

format="%s: %-12s (${RED}%s${RESET})\n"
echo "Please select setup device type (default: 1)"
printf "$format" 1 "USB-TTY-CAN" "niren USB-CAN-V3"
printf "$format" 2 "CANable" "pcan, slcan"
printf "$format" 3 "ORIGIN" "Nvidia Jetson series"

read -r type
type=${type:=1}

case $type in
    1) usbttycan ;;
    2) CANable ;;
    3) origin ;;
    *) echo "Not support type" ;;
esac

echo ""