#! /bin/sh

RED="\033[31m"
RESET="\033[0m"

usbttycan() {
    echo "Setup a USB TTY CAN device"
    echo "Please type device path (default: /dev/ttyUSB0)"
    read -r dev
    # set dev default value to /dev/ttyUSB0
    ${dev:="/dev/ttyUSB0"} &> /dev/null

    echo "setup device $dev"
    sudo chmod 777 $dev
}

CANable() {
    echo "Unsupport now please wait"
    exit -1
}

origin() {
    echo "Setup original CAN for ${RED}Nvidia Jetson AGX Xavier${RESET}"
    path=`which busybox`
    if [ -z path ]; then
        echo "Please install busybox first!"
        echo "${RED}sudo apt install busybox${RESET}"
        exit -1
    fi
    echo "Please type CAN if name (default: can0)"
    read -r dev
    # set dev default value to can0
    ${dev:="can0"} &> /dev/null

    sudo busybox devmem 0x0c303018 0xc458
    sudo busybox devmem 0x0c303010 0xc400
    sudo modprobe can
    sudo modprobe can_raw
    sudo modprobe mttcan 
    sudo ip link set $dev up type can bitrate 500000
}

echo "Please select setup device type (default: 1)"
echo "1: USB TTY CAN"
echo "2: CANable (${RED}Unsupport yet!${RESET})"
echo "3: ORIGIN (Nvidia Jetson AGX Xavier)"

read -r type

if [ -z $type ]; then
    type=1
fi

case $type in
    1) usbttycan ;;
    2) CAnable ;;
    3) origin ;;
    *) echo "Not support type" ;;
esac

echo ""